language: android
sudo: required
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-30.0.3
  - android-30
  - extra-android-m2repository
jdk:
- oraclejdk8
notifications:
  email: false
script:
- "./gradlew clean build"
before_install:
- yes | sdkmanager "platforms;android-30"
- openssl aes-256-cbc -K $encrypted_4c721a8ffc8b_key -iv $encrypted_4c721a8ffc8b_iv
  -in apiKey.properties.enc -out apiKey.properties -d
