language: android
dist: trusty
sudo: required
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-33.0.0
  - android-33
  - extra-android-m2repository
  - extra-google-m2repository
licenses:
  - '.+'
jdk:
- oraclejdk8
notifications:
  email: false
script:
- "./gradlew clean"
- "./gradlew bundleRelease"
- "./gradlew countReleaseBundleDexMethods"
before_install:
  - yes | sdkmanager "platforms;android-33"
  - openssl aes-256-cbc -K $encrypted_4c721a8ffc8b_key -iv $encrypted_4c721a8ffc8b_iv -in apiKey.properties.enc -out apiKey.properties -d
before_script:
  - chmod +x gradlew
